### ISSUE TITLE
Homepage - Top Story Layout & sign up widget area

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#12]
- [ ] Top Story layout
- [ ] Widget area for newsletter signup

![Home-Revised](https://user-images.githubusercontent.com/48263361/61743953-d2b1af00-ad5b-11e9-9f74-58a91fc6dcfe.png)

**Comment by benlk** [comment]
Holding off on this until @joshdarby is done with #8, so that this can reuse that code.

**Comment by MirandaEcho** [comment]
@josh since this one is dependent on the article one you're working on now, I'll have you do this one next.

**Comment by benlk** [comment]
Also dependent upon the homepage work being done in #13/#14.

**Comment by joshdarby** [comment]
@MirandaEcho I think the newsletter sign up portion of this might stay on hold until we answer our question about mailchimp for #11 here https://github.com/INN/umbrella-workdayminn/issues/11#issuecomment-517777128

**Comment by MirandaEcho** [comment]
@joshdarby  - Makes sense.

**Comment by MirandaEcho** [comment]
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://umn.us3.list-manage.com/subscribe/post?u=8de5bb12c5759ae9b8ec629c2&amp;id=6b4407d0f5" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name </label>
	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group input-group">
    <strong>Email Format </strong>
    <ul><li><input type="radio" value="html" name="EMAILTYPE" id="mce-EMAILTYPE-0"><label for="mce-EMAILTYPE-0">html</label></li>
<li><input type="radio" value="text" name="EMAILTYPE" id="mce-EMAILTYPE-1"><label for="mce-EMAILTYPE-1">text</label></li>
</ul>
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_8de5bb12c5759ae9b8ec629c2_6b4407d0f5" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by joshdarby** [comment]
@MirandaEcho What should the text be in the newsletter sign up section under `Story Alerts` where it says `The swallow may fly south with the sun, and the house martin or the plover may seek warmer climes in winter` in the mockup?

**Comment by joshdarby** [comment]
@MirandaEcho a PR is open for this at #32. I used 1 hr 50 min out of the 2.

**Comment by MirandaEcho** [comment]
@josh is this one done from other issues/PRs?

**Comment by joshdarby** [comment]
It's in #32 but I wouldn't call it "done" until we have an answer to https://github.com/INN/umbrella-workdayminn/issues/12#issuecomment-518814600

**Comment by MirandaEcho** [comment]
@joshdarby - that text is updatable via the widget html, correct? If so we can leave as is for now and call it done until we get the real text.

**Comment by joshdarby** [comment]
@MirandaEcho No, this one is not an html widget. It's a theme template. Only the article page newsletter sign up is a widget.

**Comment by MirandaEcho** [comment]
Right, sorry. The reference in #12 to the text from the article one confused me. I just sent a follow up email to get the text for the homepage one.
