### ISSUE TITLE
Homepage - Sidebar widget area and positioning

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#13]
- [ ] recent posts widget for post in media category
- [ ] styles

Notes on media section:
- Could be videos, podcasts, or audio. 
- Auto to most recent
- More link goes to media category landing page
- Listen button goes to detail post for that podcast/video/media item

**Comment by MirandaEcho** [comment]
![Home-Revised](https://user-images.githubusercontent.com/48263361/61744169-3d62ea80-ad5c-11e9-8b9e-3de60fa8a7c1.png)

**Comment by benlk** [comment]
For that Podcast widget, had we decided which widget would go there? Recent Posts would get us everything except the "Listen" button, which we might be able to add with CSS or a customization of the template there. https://github.com/INN/largo/blob/trunk/inc/widgets/largo-recent-posts.php#L103

**Comment by MirandaEcho** [comment]
It's all media, not just podcasts. (video, audio, podcasts) that will go in
that section, determined via a media category.  Instead of listen it will
need to be "watch/listen"? Open to suggestions.

**Comment by benlk** [comment]
Changes to the mockup:

- "Listen" becomes "more"
- "More" becomes "view all"

**Comment by benlk** [comment]
- [ ] find the icon in the files that were sent over.

**Comment by benlk** [comment]
The "icon" in https://xd.adobe.com/spec/e12ba5e6-9fe1-448a-68e4-e701056351e0-971a/ is a triangle inside a circle. It's not a defined icon.

**Comment by benlk** [comment]
Using `&#x25b6`, the html of the charcode for the 'play' character isn't workable; Apple's default emoji font forces that to have emoji presentation.

<img width="118" alt="Screen Shot 2019-08-02 at 17 17 25 " src="https://user-images.githubusercontent.com/1754187/62399348-8cbdcd80-b549-11e9-8f00-4d0379d83598.png">

**Comment by benlk** [comment]
nevermind, got it with ►:

<img width="127" alt="Screen Shot 2019-08-02 at 17 24 28 " src="https://user-images.githubusercontent.com/1754187/62399612-677d8f00-b54a-11e9-8dda-05421637327a.png">

**Comment by benlk** [comment]
Merged in #25.
