### ISSUE TITLE
Homepage - Recent stories area 

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#15]
![Home-Revised](https://user-images.githubusercontent.com/48263361/61744216-58cdf580-ad5c-11e9-9b09-2d1156a2d419.png)

**Comment by benlk** [comment]
- [ ] create widget area named "homepage bottom" for this area, just as a single-column full-width widget area
- [ ] styles for a Recent Posts widget in this area

**Comment by joshdarby** [comment]
@MirandaEcho @kaylima Does it make more sense for the title of this section to be `Recent Posts` instead of `Releated Posts`?

**Comment by benlk** [comment]
The mockup is wrong; the widget title here should be "Recent Posts"

**Comment by benlk** [comment]
It might be best to work on this in concert with #10; the styles for the recent/related stories appear pretty similar. The difference is the widget's background color.

**Comment by joshdarby** [comment]
This one is probably best being held until #25/#26 are merged so I can use the `widget.less` file that is set up in those PR's.

**Comment by joshdarby** [comment]
@MirandaEcho #30 is the PR for this. So far I have spent 1 hr 15 mins out of the 4 hours.
