### ISSUE TITLE
Homepage - News Aggregator

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#16]
Need to determine pagination and approach for this.

**Comment by MirandaEcho** [comment]
![Home-Revised](https://user-images.githubusercontent.com/48263361/61744288-8c108480-ad5c-11e9-9c65-cf7711ebfbbc.png)

**Comment by MirandaEcho** [comment]
The news aggregator on the homepage will show only 4 stories, with no slider or pagination. However, there should be a more button below that links to the rest of the aggregated stories.

**Comment by benlk** [comment]
@MirandaEcho let's check in on this before the end of today.

**Comment by benlk** [comment]
We're using Link Roundups for this, and these are Saved Links.

- [ ] check if Saved Links List Widget supports thumbnails (before anything else)
    - if yes, 2-4h styles
    - if no, ask client if necessary for thumbnails (if they say yes, that's customization of the widget, which adds time)

**Comment by benlk** [comment]
https://github.com/INN/link-roundups/blob/be0f2a93a892904bf1d55a9dfd8ccf9311822d87/inc/saved-links/class-saved-links-widget.php#L58-L60

Yes, it supports thumbnails.

2-4h styles.

**Comment by benlk** [comment]
The plugin's markup is annoying to style (see https://github.com/INN/link-roundups/issues/182) but can be overcome.

**Comment by benlk** [comment]
Merged in #26.
