### ISSUE TITLE
Footer - Logos

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#17]

**Comment by MirandaEcho** [comment]
The logos in the footer will need to contain all the sponsor logos, so there will need to be four at a time with a slider to display the rest.  @benlk  or @joshdarby  can you provide an estimate for that, please?

**Comment by joshdarby** [comment]
Assuming we will need to build a footer widget so they can dynamically add/remove logos, I'd say < 4 hours.

**Comment by MirandaEcho** [comment]
@joshdarby - can you give me a quick outline of the approach for this? Are we using a plugin, or building something custom?

**Comment by joshdarby** [comment]
My thought process was that we would just build a custom widget that allows them to add and remove logos as needed. @benlk what about you?

**Comment by benlk** [comment]
Rather than build a custom widget, we could:

1. one image widget per logo
2. set overflow on that widget area so that it scrolls horizontally
3. use display: flex to put them all in a row at the same size
3. JS that dynamically generates flex-order CSS for the widgets, so that the order changes per page view

**Comment by joshdarby** [comment]
My only concern with that is what if they want to add in another widget to the footer later on? If we're just adding multiple image widgets there wouldn't be a great way to create some sort of wrapper element for them. Other than that, I'm good with that route.

**Comment by kaylima** [comment]
@benlk  and @joshdarby  would it make sense, and perhaps save time, to set up a plugin to use in that area instead of individual widgets?

**Comment by benlk** [comment]
If we create our own plugin/widget, we'll need to make:

1. image upload handlers for arbitrary number of images
2. mechanism to remove image from widget
3. set custom link for each image

By using the Image Widgets, or any other widget that handles image upload, we don't have to reimplement that behavior.

**Comment by benlk** [comment]
oh, different meaning of "set up"

**Comment by benlk** [comment]
What's our go-to?

**Comment by MirandaEcho** [comment]
I have used this in the past: https://wordpress.org/plugins/wp-logo-showcase-responsive-slider-slider/

**Comment by MirandaEcho** [comment]
@joshdarby are there buttons on the side to scroll that I just can't see?

**Comment by joshdarby** [comment]
@MirandaEcho They're hidden through the plugin settings at the moment. Did we need them enabled?

**Comment by MirandaEcho** [comment]
We will when there are more than 4 logos, probably
