### ISSUE TITLE
Site Header and Navigation

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#2]
Create a custom site header and navigation to match the design mockups
![Home-Revised](https://user-images.githubusercontent.com/48263361/61721058-7e8fd600-ad2d-11e9-951d-e0d5710eff14.png)

**Comment by benlk** [comment]
Notes:

- still using Largo sticky nav
- donate button link using existing Largo button code, just in custom template
- search button functionality is TBD, for now can just be link to search page or the existing search form

**Comment by MirandaEcho** [comment]
- Search functionality TBD & will be separate issue if other than link to search page
- Logo forthcoming - use placeholder image for now from mockup

**Comment by joshdarby** [comment]
@benlk @MirandaEcho 

> still using Largo sticky nav

Can someone explain this requirement more? On the mobile design it shows the same header/nav as desktop. Is that just meant to be sticky as well? Or just use the actual sticky menu when scrolling?

**Comment by joshdarby** [comment]
Mobile design for reference 

![Home - Mobile](https://user-images.githubusercontent.com/18353636/62155371-aa373100-b2d6-11e9-80c3-6b88a6f109f3.png)

**Comment by benlk** [comment]
I'd make sure the custom header is responsive so it appears like this at the top of the page, and then have the unmodified Largo sticky nav appear as normal

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Site header and navigation](https://trello.com/c/ald8I40d/7-site-header-and-navigation)

**Comment by joshdarby** [comment]
We have decided to forego the normal header on mobile in lieu of just using the regular Largo mobile sticky nav.
