### ISSUE TITLE
Site Footer

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#3]
Create custom site footer to match design mockups, exclusing footer logos, which will be a separate issue. 
![Home-Revised](https://user-images.githubusercontent.com/48263361/61721141-99fae100-ad2d-11e9-9a46-28f383c32c3e.png)

**Comment by benlk** [comment]
Parts of this:
- [ ] Container solution for the sponsor logos (just these 4? Can use Image Widgets.) (30m)
- [ ] Placement/styling for sponsor logos on desktop and mobile (probably just flexbox) (<2h)
- [ ] Remove Largo boilerplate code from footer (1h)
- [ ] styles for social buttons (2h)

**Comment by MirandaEcho** [comment]
@ben we can pull removing the Largo boilerplate, but good catch. This comes back to the design mockups not necessarily being the final call for content, but instead design elements overall.

**Comment by MirandaEcho** [comment]
Social icons: Twitter and Facebook

**Comment by MirandaEcho** [comment]
Will split into separate issues: Footer <2 Hours, logos will be a separate question
