### ISSUE TITLE
Design QA: Header

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-workdayminn#33]
See below and compare to approved design:

1. Too much space to the left of donate and right of search, decrease space
2. DONATE and SEARCH are using the wrong font and weight
3. Menu links should be bigger and a lighter weight
4. Decrease height of menu area and increase height of top header (black background)
5. Pipe should be thinner and grey, not white.

![Screen Shot 2019-08-07 at 12 10 56 PM](https://user-images.githubusercontent.com/15877728/62647240-54cdd600-b90d-11e9-8de9-6f8da9014db4.png)

![wd_header_tweaks](https://user-images.githubusercontent.com/15877728/62647260-5eefd480-b90d-11e9-9db8-b6d981ebf2a5.png)

**Comment by joshdarby** [comment]
@kaylima Can you explain # 1 more? Did you mean reduce the space so that `Donate` and `Search` are in line with the content margin? 

For reference:
![Screen Shot 2019-08-07 at 4 59 01 PM](https://user-images.githubusercontent.com/18353636/62657712-1cda8900-b935-11e9-9d5f-f789fb5e7bb8.png)

**Comment by kaylima** [comment]
> @kaylima Can you explain # 1 more? Did you mean reduce the space so that `Donate` and `Search` are in line with the content margin?
> 
> For reference:
> ![Screen Shot 2019-08-07 at 4 59 01 PM](https://user-images.githubusercontent.com/18353636/62657712-1cda8900-b935-11e9-9d5f-f789fb5e7bb8.png)

It should live within it's own world of margin. I.e. always towards the left and right of the header. It's independent of the content margin. We can look at this together tomorrow AM if you'd like.

**Comment by joshdarby** [comment]
@kaylima Got it. Thanks for explaining.

**Comment by kaylima** [comment]
@joshdarby np! I'm not sure I totally did, but I hope so! Essentially they should only be a handful of pixels (est. <50px) from the very edge of the screen.
