### ISSUE TITLE
Design QA: recent posts homepage

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-workdayminn#38]
1. Increase space below “RECENT POSTS”
2. “RECENT POSTS” text should be bigger: 42px
~3. Image should be taller~
4. Reduce space between title and excerpt
5. Excerpt text should be grey, not black
6. These titles appear to be too bold, reduce weight.

![wd_recentposts_qa](https://user-images.githubusercontent.com/15877728/62652784-61f0c200-b919-11e9-8b27-34ac38b32896.png)

![Screen Shot 2019-08-07 at 1 44 05 PM](https://user-images.githubusercontent.com/15877728/62652820-75039200-b919-11e9-809b-a915a8162196.png)

**Comment by joshdarby** [comment]
@kaylima Making the image taller will probably result in it becoming distorted from being stretched out of its normal aspect ratio.

**Comment by kaylima** [comment]
> @kaylima Making the image taller will probably result in it becoming distorted from being stretched out of its normal aspect ratio.

OK. Let's keep as-is.
