### ISSUE TITLE
Homepage layout

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#4]
![Home-Revised](https://user-images.githubusercontent.com/48263361/61721229-c1ea4480-ad2d-11e9-83b8-0d17f82bbd7c.png)

**Comment by benlk** [comment]
Top story layout: 2h
Sidebar widget area and its positioning relative to featured story: 2h
Featured story layout: 2h
Related Stories area on homepage: 4h
News Aggregator (Link Roundups or Saved Links widget) styles and custom output: 4-8h, depending on how custom this is supposed to be.

**Comment by MirandaEcho** [comment]
@ben tell me more about the News Aggregator and how we can make it 4h instead of 8

**Comment by MirandaEcho** [comment]
Podcasts section:
- Auto to most recent
- More link goes to podcasts category landing page
- Listen button goes to detail post for that podcast

**Comment by MirandaEcho** [comment]
On large screens: Width will remain within container for very large screns

**Comment by MirandaEcho** [comment]
Closing, since this has been broken out into separate issues.
