### ISSUE TITLE
Navigation items to fix

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-workdayminn#45]
1. Both "contact" and "jobs" go to the contact page right now
2. Seeing 2 "ABOUT" in the sticky nav and mobile nav

**Comment by MirandaEcho** [comment]
#1 is resolved.

@joshdarby - thoughts on #2? 

Also, the logo links to the current page, rather than the site homepage, and I'm not sure how to update that.

**Comment by joshdarby** [comment]
> Also, the logo links to the current page, rather than the site homepage, and I'm not sure how to update that.

@MirandaEcho That will be fixed when I deploy #33
