### ISSUE TITLE
Post prominence showing on posts instead of categories

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-workdayminn#49]
1. Go to: http://workdayminnesota.flywheelsites.com/video-skyway-march-calling-on-st-paul-building-owners-to-cleanupyourgreed/

RESULT: showing "HOMEPAGE TOP STORY" before the title instead of the category....

EXPECT: should show category(ies) or top term

**Comment by kaylima** [comment]
![Screen Shot 2019-08-07 at 8 32 00 PM](https://user-images.githubusercontent.com/15877728/62671004-7604e580-b952-11e9-96de-ebf5698416a5.png)

**Comment by joshdarby** [comment]
@kaylima This is because `Homepage Top Story` was selected as the top term in the post instead of an actual category.
