### ISSUE TITLE
Article Page Layout

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#5]
![Article-Revised](https://user-images.githubusercontent.com/48263361/61721267-d1698d80-ad2d-11e9-93f0-eefcf95353ef.png)

**Comment by benlk** [comment]
- Widen main column width of single-column template: 2-4h? Depends a lot on what breaks.
- Change one-column template featured image display, put header data over it: 4h
- Pull quote styles: 2h
- Related Stories styles: 2-4h
- Story Alerts newsletter signup widget, code and styles: 4h if in Custom HTML widget

**Comment by MirandaEcho** [comment]
Social icons: Facebook and twitter

**Comment by MirandaEcho** [comment]
Closing issue since it has been broken out into specific issues
