### ISSUE TITLE
search page has 2 search fields

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-workdayminn#51]
1. Go to: http://workdayminnesota.flywheelsites.com/?s=union&search+submit=

RESULT: two search fields:

![Screen Shot 2019-08-07 at 8 40 11 PM](https://user-images.githubusercontent.com/15877728/62671336-ae58f380-b953-11e9-88fa-4f9f90cf5d63.png)

EXPECT: remove the search above "archives"

**Comment by joshdarby** [comment]
This was solved by just removing the "Search" widget from the main sidebar.
