### ISSUE TITLE
Multiple categories should display on posts (1 Hour)

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#64]
Top term first, then the rest alphabetically

**Comment by joshdarby** [comment]
@MirandaEcho What should the separator be for the categories? A comma? A pipe?

**Comment by kaylima** [comment]
@joshdarby let's do a small pipe similar to the right of "DONATE" in the header

**Comment by kaylima** [comment]
@joshdarby actually; what we have at the bottom of the post for the unstyled byline would be fine. that's probably the out of the box pipe styling

**Comment by joshdarby** [comment]
@MirandaEcho This is deployed to staging.
