### ISSUE TITLE
Branding material question: official colors and fonts?

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-workdayminn#7]
Info needed from the client for #1 and #6:

- [x] official colors list (can proceed based off of mockup, but will want official colors later)
- [x] official fonts list, source of fonts for same
    - headline looks like PT Sans Narrow Bold, but where would they like to source that from?

**Comment by benlk** [comment]
Fonts (all available through Adobe Fonts):
Bureau Grot Condensed Medium
Bureau Grot Condensed Bold
Bureau Grot Condensed Book
Bureau Grot Black
Classico URW

**Comment by benlk** [comment]
@MirandaEcho did they say when they sent the fonts over what each font should be used for?

by comparing the specimen at https://fonts.adobe.com/fonts/bureau-grot to the mockups, I think it's:

- Bureau Grot Condensed Bold for headlines
- Bureau Grot Condensed Black for pull quotes, and for the "MINNESOTA" in "WORKDAY MINNESOTA"
- Bureau Grot Condensed Medium for the top term, the first graf of a post, bylines, post titles in widgets, buttons, 
- Classico URW for the body text

But I don't know where they want to use Bureau Grot Black.

**Comment by MirandaEcho** [comment]
This is a developer-friendly version of the mockups:
https://xd.adobe.com/spec/e12ba5e6-9fe1-448a-68e4-e701056351e0-971a/
When you click on one of the text items, the right side displays a bunch of info about it via the specs button, including the fonts

**Comment by benlk** [comment]
That's got about two dozen colors, half duplicates, so I've reduced it to this set:

![Screen Shot 2019-07-31 at 17 13 07 ](https://user-images.githubusercontent.com/1754187/62248676-b397ca80-b3b6-11e9-987d-62c72a602406.png)

Less vars and WordPress block colors are in c81b2d0.
