### ISSUE TITLE
Article Page - Featured Image display

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#8]
- [x] Change one-column template featured image display
- [x] Put header data over top of image
- [x] Social icons: Facebook and Twitter 

![Article-Revised](https://user-images.githubusercontent.com/48263361/61743433-e872a480-ad5a-11e9-8867-fe6fe2d7bc09.png)

**Comment by benlk** [comment]
The social icons here can be the same largo buttons, just styled differently.

**Comment by joshdarby** [comment]
@MirandaEcho @benlk Did we ever find out the specifics of the background image? 

Is the background image the featured image of the post?
What happens if there is no featured image?

**Comment by MirandaEcho** [comment]
The background image will be the featured image, if no featured image then we will use the gray overlay.

**Comment by joshdarby** [comment]
@MirandaEcho In the mobile design for this, the author name is listed twice. Once above the article title and once below. On desktop it's below the article title. Should that be where it stays on mobile?

**Comment by MirandaEcho** [comment]
@joshdarby yeah, keep it consistent with the desktop design. Thanks!!

**Comment by joshdarby** [comment]
Another question: there's no black-ish overlay on the image like on desktop. Should we keep it or forego it on mobile? 

Mobile design for reference https://xd.adobe.com/spec/e12ba5e6-9fe1-448a-68e4-e701056351e0-971a/screen/4c28d863-93ff-4fc2-af57-b4ff9f1bf5e8/Article-Mobile

**Comment by MirandaEcho** [comment]
Whatever is easiest.  If they're the same level of effort, forego it since the text doesn't overlay the image like on desktop to necessitate that.

**Comment by MirandaEcho** [comment]
@joshdarby  - I don't see the blue category tag above the headline. Is that just because there isn't a category assigned to the article on the homepage?

**Comment by joshdarby** [comment]
@MirandaEcho Probably. Which article are you looking at?

**Comment by MirandaEcho** [comment]
@joshdarby  http://workdayminnesota.flywheelsites.com/the-mac-commission-gets-heated/

**Comment by joshdarby** [comment]
@MirandaEcho Yea, that one didn't have a top term set. Try refreshing.
