### ISSUE TITLE
Article Page - Pull Quote styles 

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-workdayminn#9]
![Article-Revised](https://user-images.githubusercontent.com/48263361/61743567-325b8a80-ad5b-11e9-9e48-c186d0550c46.png)

**Comment by benlk** [comment]
Are they switching to Gutenberg, or sticking with the classic editor? If they haven't already started using the classic editor, I'd recommend starting them on the block editor.

The answer to the question of Gutenberg or Classic Editor affects how we're styling pull quotes.

**Comment by benlk** [comment]
Gutenberg.

**Comment by benlk** [comment]
- [ ] on the single-column layout, alignleft blocks move left by the same amount that the alignwide block moves left. 
- [ ] alignright same, but to the right
- [ ] https://github.com/INN/largo/issues/1748, in frontend and in editor
- [ ] font
- [ ] green `"` before and after on one variant
- [ ] orange `"` before and after, cream background on the other variant
